#!/usr/bin/env python

import os
from diffusers import DiffusionPipeline


model_id = "XpucT/Deliberate"
MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)
